### PR TITLE
fix: get credential by said 404 response

### PR DESCRIPTION
**Pull request by iFergal**
`rgy.reger.cloneCred` or `cloneCreds` will cause a 500 error if the credential does not exist:
```
  File "/Users/fergaloconnor/dev/keri/cardano-foundation/keria/venv/lib/python3.12/site-packages/keri/vdr/viring.py", line 488, in cloneCred
    prefixer, seqner, saider = self.cancs.get(keys=(said,))
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

I fixed this in keripy to throw a missing entry error: https://github.com/WebOfTrust/keripy/pull/841

So just catching that and returning 404.

### CODE REVIEW

**Comment by iFergal** [comment]
Actually, there is `kering.MissingEntryError` already in keripy. I think this would be better to throw from keripy - I will look at this at some point. Marking as draft.

**Comment by iFergal** [comment]
https://github.com/WebOfTrust/keripy/pull/841 merged, will update this when there's a release with it and I'm free

**Comment by iFergal** [comment]
cc @2byrds

**Review by 2byrds — APPROVED** [review]
LGTM

**Pull request merged**
