### PR TITLE
Refactor Serials to Kinds to match keripy

### PR DESCRIPTION
**Pull request by SmithSamuelM**

### CODE REVIEW

**Comment by SmithSamuelM** [comment]
Needs to update github tests to test against https://github.com/WebOfTrust/keripy/pull/826

**Comment by m00sey** [comment]
@m00sey to create keripy dev tag

**Comment by m00sey** [comment]
https://pypi.org/project/keri/1.2.0.dev12/ published

**Comment by iFergal** [comment]
@m00sey This can merge if we get a `dev13` version which is required for the latest changes to `encrypter.encrypt`. Tested locally against keripy `main` and all the tests pass.

**Comment by iFergal** [comment]
@SmithSamuelM Phil published `1.2.0-dev13` so if this PR is updated it should be ready to merge

**Review by m00sey — APPROVED** [review]

**Review by m00sey — CHANGES_REQUESTED** [review]
Introduces new errors:

`TypeError: SaltyManager.rotate() missing 2 required positional arguments: 'kidx' and 'transferable'`
`TypeError: Encrypter.encrypt() got an unexpected keyword argument 'prim'`

**Comment by kentbull** [comment]
#294 duplicates this.

**Comment by iFergal** [comment]
This can be closed now that #294 has merged!

**Pull request closed without merging**
