### PR TITLE
refactor: serials to kinds and upgrade to keripy version

### PR DESCRIPTION
**Pull request by iFergal**
Supersedes #275 - same changes, just pointing to the correct dev release.

### CODE REVIEW

**Comment by iFergal** [comment]
cc @m00sey

**Comment by kentbull** [comment]
This looks like a duplicate of #275

**Comment by iFergal** [comment]
@kentbull It's an intentional duplicate to make the tests pass, based off of the other PR as I couldn't push to Sam's fork. So once merged the other one should be closed

**Review by 2byrds — APPROVED** [review]
LGTM

**Pull request merged**
