### PR TITLE
Support for https endpoints in witnesses, controllers and agents

### PR DESCRIPTION
**Pull request by rodolfomiranda**

### CODE REVIEW

**Comment by pfeairheller** [comment]
See my comment to https://github.com/WebOfTrust/keripy/pull/555.  Same applies here

**Comment by rodolfomiranda** [comment]
This PR is in line with the merged PR on `keripy` https://github.com/WebOfTrust/keripy/pull/555

**Comment by psteniusubi** [comment]
Hi @rodolfomiranda 
I just tried this fix with some smallish issues. 
My https witness endpoints have no port, for example `https://witness-5642.io.ubidemo1.com`
This causes keri to generate invalid oobi urls with `:None` as port, like this `https://witness-5642.io.ubidemo1.com:None`

**Comment by rodolfomiranda** [comment]
YEs, you are correct. We faced the same issues. I'll add that change as well.

**Comment by psteniusubi** [comment]
It looks like this issue exists in many places of keripy too. 
I think it would be simpler to generate urls with [urljoin](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin), using the configured url as base.
Thanks!

**Comment by rodolfomiranda** [comment]
I'm replacing this PR with #103

**Pull request closed without merging**
