### PR TITLE
fix: key states query operation internal server error (ksn.ked does not exist)

### LINKED ISSUE #150: HTTP 500 Internal Server Error when querying key states without providing sequence number
See reproduction test from signify-ts: https://github.com/WebOfTrust/signify-ts/compare/development...lenkan:signify-ts:resolve-keystates-error

# Steps to reproduce

1. Create two clients
1. Create AID in each client
1. Resolve OOBIs
1. Call /keystates/query without the `sn` parameter.

# Actual result

KERIA responds with HTTP 500 Internal Server error when fetching the operation. Stack trace:

```
signify-ts-keria-1  | 2023-12-18 09:54:07 [FALCON] [ERROR] GET /operations/query.EGsuRt_D1jDhizs_gzg35oHJO1lK2vklZYCZhAqIm7u3 => Traceback (most recent call last):
signify-ts-keria-1  |   File "falcon/app.py", line 365, in falcon.app.App.__call__
signify-ts-keria-1  |   File "/keria/src/keria/core/longrunning.py", line 384, in on_get
signify-ts-keria-1  |     if (operation := agent.monitor.get(name)) is None:
signify-ts-keria-1  |   File "/keria/src/keria/core/longrunning.py", line 137, in get
signify-ts-keria-1  |     operation = self.status(op)
signify-ts-keria-1  |   File "/keria/src/keria/core/longrunning.py", line 282, in status
signify-ts-keria-1  |     if ksn and ksn.ked['d'] == kever.serder.said:
signify-ts-keria-1  | AttributeError: 'KeyStateRecord' object has no attribute 'ked'
signify-ts-keria-1  |
```

# Expected result

KERIA operation is resolved with the latest key state (?)

### PR DESCRIPTION
**Pull request by lenkan**
Closes #150 

I could not find any tests for this feature to update and currently do not have time to write something from scratch. Creating the PR anyway and you can decide if you want to takeover, wait for the tests or just merge it.

We are still not able to retrieve the updated state by using the key states query endpoint though. But that is another issue.

### CODE REVIEW

**Comment by pfeairheller** [comment]
If you rebase on development now, these tests should pass and we can merge it in

**Comment by lenkan** [comment]
> If you rebase on development now, these tests should pass and we can merge it in

:+1: Rebased it now.

**Review by pfeairheller — CHANGES_REQUESTED** [review]
@lenkan Can you add a test for this endpoint so we don't break it again?  (Yes, I know there wasn't a test to begin with).

**Comment by lenkan** [comment]
Yes, was planning to give it a go. It will at the earliest be tomorrow. Probably not until next week due to the holidays.

**Comment by m00sey** [comment]
@lenkan any update on adding the test?

**Comment by lenkan** [comment]
No, sorry. Been AFK for two weeks. Anyone feel free to pick it up if they need it done more urgently than myself. :)

**Comment by pfeairheller** [comment]
This was fixed in another PR already merged.

**Pull request closed without merging**
